const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
const { requireAuth } = require('../middleware/authMiddleware');
const { requireAdmin, requireSuperAdmin } = require('../middleware/roleMiddleware');

router.get('/admin/dashboard', requireAuth, requireAdmin, adminController.getDashboard);
router.get('/admin/activity', requireAuth, requireAdmin, adminController.getAdminActivity);
router.get('/admin/campaigns', requireAuth, requireAdmin, adminController.getPendingCampaigns);
router.get('/admin/fundraisers/pending', requireAuth, requireAdmin, adminController.getPendingCampaigns);
router.get('/admin/fundraisers/:id', requireAuth, requireAdmin, adminController.getCampaignReview);
router.get('/admin/fundraisers/:id/review', requireAuth, requireAdmin, adminController.getCampaignReview);
router.patch('/admin/fundraisers/:id', requireAuth, requireAdmin, adminController.reviewCampaign);
router.put('/admin/fundraisers/:id', requireAuth, requireAdmin, adminController.reviewCampaign);
router.patch('/admin/fundraisers/:id/approve', requireAuth, requireAdmin, adminController.approveCampaign);
router.put('/admin/fundraisers/:id/approve', requireAuth, requireAdmin, adminController.approveCampaign);
router.patch('/admin/fundraisers/:id/reject', requireAuth, requireAdmin, adminController.rejectCampaign);
router.put('/admin/fundraisers/:id/reject', requireAuth, requireAdmin, adminController.rejectCampaign);
router.patch('/admin/campaigns/:id', requireAuth, requireAdmin, adminController.reviewCampaign);
router.put('/admin/campaigns/:id', requireAuth, requireAdmin, adminController.reviewCampaign);
router.get('/admin/donations', requireAuth, requireAdmin, adminController.getAdminDonations);
router.get('/admin/users', requireAuth, requireAdmin, adminController.getAdminUsers);
router.get('/admin/users/:id', requireAuth, requireAdmin, adminController.getAdminUserById);
router.patch('/admin/users/:id/status', requireAuth, requireAdmin, adminController.updateUserStatus);
router.get('/admin/admins', requireAuth, requireSuperAdmin, adminController.getAdmins);
router.get('/admin/admin-candidates', requireAuth, requireSuperAdmin, adminController.getAdminCandidates);
router.post('/admin/admins', requireAuth, requireSuperAdmin, adminController.addAdmin);
router.delete('/admin/admins/:id', requireAuth, requireSuperAdmin, adminController.removeAdmin);

module.exports = router;
